apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "api-syncagent:cloudnative-pg"
rules:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "api-syncagent:cloudnative-pg"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "api-syncagent:cloudnative-pg"
subjects:
  - kind: ServiceAccount
    name: "kcp-api-syncagent"
    namespace: kcp-sync-agent
